version: "3.8"

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=spring-batch
      - MYSQL_ROOT_PASSWORD=dbadmin

    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8000:8080'
    command: start-dev

volumes:
  db:
    driver: local