version: "3.8"

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=spring-batch
      - MYSQL_ROOT_PASSWORD=dbadmin

    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

#  keycloak:
#    image: quay.io/keycloak/keycloak:19.0
#    container_name: keycloak
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - KEYCLOAK_IMPORT=/kc_data/realm-data.json
#    volumes:
#      - ./kc_data:/kc_data
#    ports:
#      - '8000:8080'
#    command: start-dev

  keycloak-db:
    image: postgres
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    volumes:
      - ./kc_data:/imports

    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /imports/realm-export-updated.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8000:8080
    depends_on:
      - keycloak-db

volumes:
  db:
    driver: local
  keycloak_postgres_data:
    driver: local