spring:
  application:
    name: spring-batch

  datasource:
    url: jdbc:mysql://localhost:3306/spring-batch
    username: root
    password: dbadmin

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  main:
    allow-bean-definition-overriding: true

server:
  port: 5000